pdm: disable symlinking to cache.
Because of the wasmtime's implementation of sandboxing, YoWASP binaries
cannot read symlinks that point outside of the mounts they can access.
The symptom of that is an error message like this:

    ERROR: Can't open input file `/share/ice40/cells_sim.v' for reading: Operation not permitted

This needs to be fixed properly (probably by making YoWASP binaries be
Wasm components) but in the meantime this addresses immediate breakage.