cli: fix intermittent analyzer error.
Due to a logic error, sometimes analyzer would crash with a message
similar to:

    vcd.writer.VCDPhaseError: Out of order timestamp: 171587604